---

image: docker:latest

variables:
  DOCKER_VERSION: "18.06"
  DOCKER_HOST: tcp://localhost:2375 # Nécessaire depuis le passage sur des runner sur l'executor Kubernetes
  CONTAINER_IMAGE: socialgouv/dila2sql

services:
  - docker:dind

stages:
  - "Build local Docker images"
  - "Test"
  # - "Deploy image to Docker Hub"

prepare-dila2sql-image:
  stage: "Build local Docker images"
  image: docker:$DOCKER_VERSION
  services:
  - docker:dind
  before_script:
  - docker login $CI_REGISTRY -u gitlab-ci-token -p $CI_JOB_TOKEN
  script:
  - docker build --cache-from dila2sql:$CI_COMMIT_BEFORE_SHA -t "$CI_REGISTRY_IMAGE/dila2sql:$CI_COMMIT_SHA" packages/dila2sql
  - docker push "$CI_REGISTRY_IMAGE/dila2sql:$CI_COMMIT_SHA"

test-dila2sql:
  stage: "Test"
  image: docker:$DOCKER_VERSION
  services:
  - docker:dind
  script:
  - docker run -t "$CI_REGISTRY_IMAGE/dila2sql:$CI_COMMIT_SHA" tox
