---

image: docker:latest

variables:
  DOCKER_VERSION: "18.06"
  DOCKER_HOST: tcp://localhost:2375 # Nécessaire depuis le passage sur des runner sur l'executor Kubernetes
  CONTAINER_IMAGE: socialgouv/dila2sql
  PREVIOUS_CI_IMAGE_DILA2SQL: "$CI_REGISTRY_IMAGE/dila2sql_ci:$CI_COMMIT_BEFORE_SHA"
  CI_IMAGE_DILA2SQL: "$CI_REGISTRY_IMAGE/dila2sql_ci:$CI_COMMIT_SHA"
  PUBLIC_IMAGE_DILA2SQL: "$CI_REGISTRY_IMAGE/dila2sql:$CI_COMMIT_SHA"
  PUBLIC_IMAGE_DILA2SQL_API: "$CI_REGISTRY_IMAGE/dila2sql_api:$CI_COMMIT_SHA"

services:
  - docker:dind

stages:
  # - "Build CI Docker images"
  # - "Run Tests"
  - "Publish Docker images"

# build-ci-docker-image-dila2sql:
#   stage: "Build CI Docker images"
#   image: docker:$DOCKER_VERSION
#   services:
#   - docker:dind
#   before_script:
#   - docker login $CI_REGISTRY -u gitlab-ci-token -p $CI_JOB_TOKEN
#   script:
#   - >-
#     docker build
#     --cache-from $PREVIOUS_CI_IMAGE_DILA2SQL
#     -t $CI_IMAGE_DILA2SQL
#     packages/dila2sql
#   - docker push $CI_IMAGE_DILA2SQL

# run-tests-dila2sql:
#   stage: "Run Tests"
#   image: docker:$DOCKER_VERSION
#   services:
#   - docker:dind
#   script:
#   - docker run -t $CI_IMAGE_DILA2SQL tox

# publish-docker-image-dila2sql:
#   stage: "Publish Docker images"
#   image: docker:$DOCKER_VERSION
#   services:
#   - docker:dind
#   before_script:
#   - docker login $CI_REGISTRY -u gitlab-ci-token -p $CI_JOB_TOKEN
#   script:
#   - >-
#     docker build
#     --cache-from $CI_IMAGE_DILA2SQL
#     -t $PUBLIC_IMAGE_DILA2SQL
#     packages/dila2sql
#   - docker push $PUBLIC_IMAGE_DILA2SQL

publish-docker-image-dila2sql-api:
  stage: "Publish Docker images"
  image: docker:$DOCKER_VERSION
  services:
  - docker:dind
  before_script:
  - docker login $CI_REGISTRY -u gitlab-ci-token -p $CI_JOB_TOKEN
  script:
  - >-
    docker build
    --cache-from $PUBLIC_IMAGE_DILA2SQL_API
    -t $PUBLIC_IMAGE_DILA2SQL_API
    packages/api
  - docker push $PUBLIC_IMAGE_DILA2SQL_API
