image: docker:latest

variables:
  DOCKER_HOST: tcp://localhost:2375 #Nécessaire depuis le passage sur des runner sur l'executor Kubernetes
  CONTAINER_IMAGE: socialgouv/legi.py

services:
  - docker:dind

stages:
  - test
  - build

test:
  image: python:3.6
  stage: test
  script:
    - apt-get update && apt-get install -y libarchive13
    - python3 -m pip install tox
    - tox

build:
  stage: build
  script:
    - docker pull $CONTAINER_IMAGE:latest || true # to get cache layer
    - docker build --cache-from $CONTAINER_IMAGE:latest -t $CONTAINER_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker build --cache-from $CONTAINER_IMAGE:latest -t $CONTAINER_IMAGE:latest .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CONTAINER_IMAGE:latest
