version: "3"
services:
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_USER: dila2sql
      POSTGRES_PASSWORD: dila2sql
    ports:
      - "5442:5432"
  api:
    image: dila2sql-api
    environment:
      DB_HOST: db
      DB_USER: dila2sql
      DB_PASSWORD: dila2sql
    ports:
      - "3001:8080"
  dila2sql:
    image: dila2sql
    environment:
      DB_HOST: db
      DB_USER: dila2sql
      DB_PASSWORD: dila2sql
